# Generated by Django 5.1.6 on 2025-03-24 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=200, verbose_name='Телефон')),
                ('tgid', models.CharField(blank=True, max_length=200, verbose_name='айди телеги')),
                ('tgname', models.CharField(blank=True, max_length=200, verbose_name='имя телеги')),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('djuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientHook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=200, verbose_name='Телефон')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Имя')),
                ('clientuser', models.ManyToManyField(to='tgusers.client')),
            ],
        ),
    ]
