# Generated by Django 5.1.6 on 2025-04-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgusers', '0002_remove_client_is_active_remove_client_is_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='about',
            field=models.CharField(blank=True, max_length=1000, verbose_name='О компании'),
        ),
    ]
